services:
  pbstream-frontend:
    build: .
    container_name: pbstream-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - pocketbase_url=http://pbstream-database:8090
  pbstream-database:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pbstream-database
    restart: unless-stopped
    expose:
      - 8090
    ports:
      - "8090:8090"
    volumes:
      - ./pb/pb_data:/pb_data
      - ./pb/pb_public:/pb_public
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5